In [1]:
import pandas as pd

inventory = pd.read_pickle('/home/max/chtl/data/processed/inventory.pkl')
loans = pd.read_pickle('/home/max/chtl/data/processed/loans.pkl')
item_types = pd.read_pickle('/home/max/chtl/data/processed/item-types.pkl')

In [2]:
from collections import defaultdict

# For each "Item Type", create a list that includes itself and all descendants
descendants = defaultdict(lambda: set())

for ix, item_type in item_types.iterrows():
    # Add itself for convenience
    descendants[item_type['Type']].add(item_type['Type'])
    # Add the child to it's parent's descendants list.
    descendants[item_type['Parent Type']].add(item_type['Type'])
    
# Remove the defaultdict, so we don't accidentally access keys that don't exist
descendants = dict(descendants)
descendants

{'Hand Tools': {'Augers & Drain Openers',
  'Axes',
  'Bits, Drivers and Accessories',
  'Brace & Bits',
  'Brushes & Rollers',
  'Buckets',
  'Caulk Guns',
  'Chisels & Gouges',
  'Clamps & Brackets',
  'Cleaning Brushes',
  'Clipboards',
  'Conduit Benders',
  'Crimpers',
  'Cultivators',
  'Dollies',
  'Drill Press (hand)',
  'Drills',
  'Drywall Tools',
  'Edgers',
  'Electrical & Data Tools',
  'Extension Poles',
  'Files, Awls & Punches',
  'Fuel Containers',
  'Gear Pullers',
  'Hammers & Mallets',
  'Hand Air Pumps',
  'Hand Saws',
  'Hand Shovel',
  'Hand Tool Sets',
  'Hand Tools',
  'Hex Keys',
  'Hoists & Trolleys',
  'Jigs',
  'Knives',
  'Ladders',
  'Lawn Care (other)',
  'Lawn Mower',
  'Locks and Security',
  'Machete',
  'Marking',
  'Measuring & Layout Tools',
  'Misc Hand Tools',
  'Mixers & Dispensers',
  'Nail Sets',
  'Paint Can Openers',
  'Pickaxes & Mattocks',
  'Pipe Cutters',
  'Pitchfork',
  'Planes',
  'Planters',
  'Pliers, Cutters, and Snips',
  'Plug Cutters',
  'Pruners',
  'Pry Bars & Crowbars',
  'Rakes',
  'Rivet Tools',
  'Roof Brackets',
  'Sanders',
  'Saw Blades',
  'Scrapers',
  'Screw Extractors',
  'Screwdrivers',
  'Scythes, Sickles & Machetes',
  'Sharpeners',
  'Shears',
  'Shovels & Digging',
  'Squeegees',
  'Staple Guns',
  'Strippers',
  'Tap and Die',
  'Testers (hand held)',
  'Tin Snips',
  'Tool Stands & Work Tables',
  'Trimmers',
  'Trowels & Floats',
  'Tube Cutters',
  'Vise Grips',
  'Watering Tools',
  'Winches',
  'Woodworking Kits',
  'Wrenches'},
 'Tools': {'Aerial Equipment',
  'Air & Pneumatic Tools',
  'Animal & Rodent Control',
  'Automotive Tools',
  'Bike Tools',
  'Chains, Ropes, and Straps',
  'Covers & Tarps',
  'Farm Tools',
  'Fencing Tools',
  'Flooring Tools',
  'Garden Tools',
  'Hand Tools',
  'Heavy Equipment',
  'Magnifiers',
  'Material Handling Equipment',
  'Meters & Diagnostics',
  'Plumbing Tools',
  'Power Tools',
  'Propane & Gas Powered Tools',
  'Safety Equipment',
  'Soil Augers',
  'Tool Kits & Storage',
  'Tree & Orchard Care Tools',
  'Welding',
  'Wheelbarrows & Wagons'},
 'Power Tools': {'Corded & Plug-in',
  'Cordless Power Tools',
  'Grinders',
  'Joiners',
  'Lathes',
  'Power Sharpeners',
  'Power Tool Accessories',
  'Power Tools'},
 'Shovels & Digging': {'Digging Fork',
  'Drain Spade Shovel',
  'Planters Shovel',
  'Roofing Shovel',
  'Round Point Shovel',
  'Shovels',
  'Shovels & Digging',
  'Snow Shovels',
  'Sod Lifter',
  'Spade Shovel',
  'Square Shovel'},
 'Rakes': {'Concrete Rake',
  'Expansion Rake',
  'Hand Rake',
  'Leaf Rake',
  'Metal Garden Rake',
  'Rakes',
  'Row Marking Rake',
  'Soil Rakes',
  'Steel Rake',
  'Thatching Rake',
  'Weeding Rake',
  'Wooden Leaf Rake'},
 'Pruners': {'Fruit Pickers',
  'Hand Pruner',
  'Loppers',
  'Pruners',
  'Telescopic Pruner'},
 'Axes': {'Axes', 'Grinding Stones', 'Hand Axe', 'Hatchet', 'Maul', 'Wedge'},
 'Hand Saws': {'Back Saws',
  'Bow Saws',
  'Coping Saws',
  'Crosscut Saws',
  'Drywall Saws',
  'Hack Saws',
  'Hand Miter Saws',
  'Hand Saws',
  'Hole Saw Kits',
  'Hole Saws',
  'Key Hole Saws',
  'Rebar Cutters & Benders',
  'Tenon Saws'},
 'Wrenches': {'Adjustable Wrench',
  'Basin Wrench',
  'Belt Strap Wrenches',
  'Chain Wrench',
  'Lock Nut Wrench',
  'Open End Wrench',
  'Pipe Wrenches',
  'Spanner Wrenches',
  'Torque Wrench',
  'Weed Wrench',
  'Wrench Sets',
  'Wrenches'},
 'Measuring & Layout Tools': {'Balance Scales',
  'Calipers',
  'Chalklines',
  'Compasses (drawing)',
  'Contour Gauges',
  'Laser Levels',
  'Levels',
  'Measuring & Layout Tools',
  'Plumb Bob',
  'Rulers',
  'Squares',
  'String Lines',
  'Stud finder',
  'T-Bevels',
  'Tape Measures',
  'Yardsticks'},
 'Marking': {'Marking'},
 'Scrapers': {'2-in-1 Glazing Tools',
  'Manual Mutt Scraper',
  'Paint Scraper',
  'Scrapers',
  'Sidewalk Ice Scraper'},
 'Planes': {'Planes', 'Rebate Planes', 'Shoulder Planes', 'Two Handed Planes'},
 'Chisels & Gouges': {'Cement Chisels',
  'Chisels & Gouges',
  'Cold Chisels',
  'Wood Chisels'},
 'Drills': {'Drills'},
 'Bits, Drivers and Accessories': {'Bits, Drivers and Accessories',
  'Drill Bits',
  'Screw Bits'},
 'Screwdrivers': {'Flat Screwdrivers',
  'Phillips Screwdrivers',
  'Robertson Screwdrivers',
  'Screwdriver Sets',
  'Screwdrivers',
  'Torx Screwdrivers'},
 'Clamps & Brackets': {'90 Degree Clamps',
  'Bar Clamps',
  'C-Clamps',
  'Clamps & Brackets',
  'Corner Clamp',
  'Drill Press Clamps',
  'F-Clamps',
  'Hand Clamps',
  'Pipe Clamps',
  'Quick Grip Clamp',
  'Vises',
  'Web Clamps',
  'Wood Clamp'},
 'Saw Blades': {'Dado Saw Blades',
  'Miter Saw Blades',
  'Saw Blades',
  'Table Saw Blades'},
 'Hammers & Mallets': {'Ball Peen Hammers',
  'Brick Hammers',
  'Claw Hammers',
  'Dead Blow Hammers',
  'Framing Hammers',
  'Hammers & Mallets',
  'Plastic Tip Hammers',
  'Rip Hammers',
  'Rubber Mallets',
  'Sledgehammers',
  'Tack Hammers'},
 'Ladders': {'Extension Ladder',
  'Ladder Leveler',
  'Ladder Stabilizer',
  'Ladders',
  'Multi Ladder',
  'Painters Platform',
  'Step Ladders',
  'Stepstools',
  'Straight Ladder',
  'Walk Board'},
 'Knives': {'Knives',
  'Linoleum Knives',
  'Putty Knife',
  'Utility Knives',
  'Wall Knives'},
 'Pliers, Cutters, and Snips': {'Bolt Cutters',
  'Box Cutters',
  'Cement Sheet Cutters',
  'Fence Plier',
  'Lineman Plier',
  'Locking Pliers',
  'Needle Nose Pliers',
  'Pliers, Cutters, and Snips',
  'Slip Joint Pliers',
  'Wire Cutters'},
 'Buckets': {'Buckets'},
 'Extension Poles': {'Extension Poles'},
 'Brushes & Rollers': {'Brushes & Rollers',
  'Counter Brush',
  'File Brushes',
  'Linoleum Roller',
  'Paint Guide',
  'Paint Roller Frame',
  'Paint Rollers',
  'Paste Brush',
  'Roller Tool',
  'Round Dust Brush',
  'Sharp Bristle Brushes',
  'Smoothing Brush'},
 'Sanders': {'Sanders'},
 'Strippers': {'Strippers'},
 'Crimpers': {'Crimpers'},
 'Pry Bars & Crowbars': {'Crow Bar with Chisel Ends',
  'Crowbars',
  'Nail Puller',
  'Pry Bar',
  'Pry Bars & Crowbars',
  'Spud Bar',
  'Wonder Bar'},
 'Corded & Plug-in': {'Buffers',
  'Chargers',
  'Corded & Plug-in',
  'Corded Grinders',
  'Corded Mowers',
  'Corded Trimmers',
  'Drill Press (power)',
  'Drill Press Accessories',
  'Electric Air Pumps',
  'Electric Augers & Drain Openers',
  'Electric Chippers',
  'Electric Dehydrators',
  'Electric Jackhammers',
  'Electric Leaf Blower',
  'Electric Mixers & Dispensers',
  'Electric Mutt Scraper',
  'Electric Nailers',
  'Electric Pumps',
  'Electric Staple Guns',
  'Engraver',
  'Extension Cords',
  'Jointers',
  'Meters',
  'Oscillating Multi Tools',
  'Paint Sprayer',
  'Power Drills',
  'Power Saws',
  'Pressure Washers',
  'Reciprocating Saws',
  'Rotary Tools',
  'Router Accessories',
  'Router Bits',
  'Routers',
  'Sanders & Planers',
  'Soldering & Heat Guns',
  'Steam Cleaners',
  'String Trimmers',
  'Testers',
  'Thickness Planer',
  'Vacuum Cleaners',
  'Wallpaper Steamer'},
 'Cordless Power Tools': {'Cordless Drills',
  'Cordless Finish Nailers',
  'Cordless Grinders',
  'Cordless Hammer Drills',
  'Cordless Hedge Trimmers',
  'Cordless Impact Drivers',
  'Cordless Jackhammers',
  'Cordless Jigsaws',
  'Cordless Leaf Blowers',
  'Cordless Mowers',
  'Cordless Oscillating Multi Tool',
  'Cordless Power Tools',
  'Cordless Routers',
  'Cordless Sanders',
  'Cordless Saws',
  'Cordless Screwdrivers',
  'Cordless String Strimmers',
  'Cordless Tool Batteries',
  'Cordless Trimmers',
  'Cordless Vacuums',
  'Flashlights'},
 'Cordless Drills': {'Cordless Drills'},
 'Flashlights': {'Flashlights'},
 'Cordless Trimmers': {'Cordless Trimmers'},
 'Cordless Saws': {'Cordless Circular Saw', 'Cordless Saws'},
 'Power Drills': {'Hammer Drills',
  'Power Drill 1/2in',
  'Power Drill 3/8in',
  'Power Drills'},
 'Power Saws': {'Band Saws',
  'Chop Saws',
  'Circular Saws',
  'Corded Miter Saws',
  'Jig Saws',
  'Power Saws',
  'Radial Arm Saws',
  'Radial Chop Saws',
  'Scroller Power Saws',
  'Table Saws',
  'Wet Tile Saws'},
 'Corded Mowers': {'Corded Mowers'},
 'Spade Shovel': {'Spade Shovel'},
 'Square Shovel': {'Square Shovel'},
 'Hand Tool Sets': {'Hand Tool Sets'},
 'Air & Pneumatic Tools': {'Air & Pneumatic Tools',
  'Air Brad Nailers',
  'Air Cut-Off Tools',
  'Air Disc Sanders',
  'Air Finish Nailers',
  'Air Framing Nailers',
  'Air Hammers',
  'Air Hammers with Chisel',
  'Air Ratchets',
  'Air Sanders',
  'Air Staplers',
  'Air Tool Sets',
  'Air Torque Wrenches',
  'Air Wrenches',
  'Compressors',
  'Jacks',
  'Pneumatic Jackhammers'},
 'Compressors': {'Compressors'},
 'Air Tool Sets': {'Air Tool Sets'},
 'Step Ladders': {'Step Ladders'},
 'Stepstools': {'Stepstools'},
 'Corded Trimmers': {'Corded Trimmers',
  'Electric Hedge Trimmers',
  'Electric Lawn Edger',
  'Electric String Trimmer'},
 'Trimmers': {'Manual Hedge Trimmers', 'Trimmers'},
 'Metal Garden Rake': {'Metal Garden Rake'},
 'Wooden Leaf Rake': {'Wooden Leaf Rake'},
 'Expansion Rake': {'Expansion Rake'},
 'Hand Rake': {'Hand Rake'},
 'Round Point Shovel': {'Round Point Shovel'},
 'Meters': {'Electric Usage Meter', 'Meters'},
 'Electric Usage Meter': {'Electric Usage Meter'},
 'Extension Cords': {'Extension Cords'},
 'Chainsaws': {'16 Inch Gas Chainsaws',
  '20 Inch Gas Chainsaws',
  'Chainsaw Bar Covers',
  'Chainsaw Bars',
  'Chainsaws',
  'Electric 12 in Chainsaws',
  'Electric 16 in Chainsaws'},
 'Tree & Orchard Care Tools': {'Bucksaws',
  'Chainsaws',
  'Felling Wedges',
  'Fruit Choppers & Munchers',
  'Fruit Presses',
  'Orchard Sprayers',
  'Pole Pickers',
  'Pruning Saws',
  'Pruning Shears',
  'Tree & Orchard Care Tools',
  'Tree Pullers',
  'Wood Splitters'},
 'Misc Hand Tools': {'Misc Hand Tools'},
 'Pickaxes': {'Pickaxes'},
 'Pickaxes & Mattocks': {'Cutter Mattocks',
  'Grubber Mattocks',
  'Pick Mattocks',
  'Pickaxes',
  'Pickaxes & Mattocks'},
 'Electric Chippers': {'Electric Chippers'},
 'Weeders': {'Hand Roller Weeders', 'Hoe Weeders', 'Weeders'},
 'Garden Tools': {'Bed Shapers',
  'Branch Cutters',
  'Broad Forks',
  'Bulb Planters',
  'Bush Cutters',
  'Compost Aerators',
  'Dibbers',
  'Garden Gloves',
  'Garden Hoses',
  'Garden Spades',
  'Garden Tools',
  'Garden Trowels',
  'Hand Tillers',
  'Hoes',
  'Hoop Benders',
  'Irrigation Pumps',
  'Kneeling Pads',
  'Lawn Dethatchers',
  'Lawn Scarifiers',
  'Planting Templates',
  'Secateurs',
  'Seed Processing Tools',
  'Seeders',
  'Small Tillers',
  'Sod Tampers',
  'Weeders'},
 'Hoes': {'Edging Hoes', 'Hoes'},
 'Planters Shovel': {'Planters Shovel'},
 'Brooms & Mops': {'Brooms',
  'Brooms & Mops',
  'House Broom',
  'Mops',
  'Push Brooms'},
 'Cleaning': {'Brooms & Mops', 'Cleaning'},
 'Push Brooms': {'Push Brooms'},
 'Edgers': {'Cement Edger', 'Edgers', 'Manual Lawn Edger'},
 'Welders': {'Welders'},
 'Welding': {'Arc Cutting and Gouging',
  'Gas Welding',
  'MIG Welding',
  'Stick Welding',
  'TIG Welding',
  'Welders',
  'Welding',
  'Welding Safety Equipment',
  'Welding Supplies & Accessories'},
 'Radial Chop Saws': {'Radial Chop Saws'},
 'Chop Saws': {'Chop Saws'},
 'Circular Saws': {'Circular Saws', 'Worm Drive Circular Saws'},
 'Worm Drive Circular Saws': {'Worm Drive Circular Saws'},
 'Grinders': {'Angle Grinders', 'Bench Grinders', 'Die Grinders', 'Grinders'},
 'Bench Grinders': {'Bench Grinders'},
 'Levels': {'Levels'},
 'Tape Measures': {'Tape Measures'},
 'Jacks': {'House Jack', 'Jacks', 'Trolly Jacks'},
 'Winches': {'Come Along Bars', 'Come-alongs', 'Drywall Lifts', 'Winches'},
 'Come-alongs': {'Come-alongs'},
 'Tool Stands & Work Tables': {'Router Table',
  'Saw Horses',
  'Table Rollers',
  'Tool Bench Work Mate',
  'Tool Stands & Work Tables'},
 'Saw Horses': {'Saw Horses'},
 'Table Rollers': {'Table Rollers'},
 'Jack Stands': {'Jack Stands'},
 'Automotive Tools': {'Automotive Funnels',
  'Automotive Jacks',
  'Automotive Pressure Gauges',
  'Automotive Ramps',
  'Automotive Tools',
  'Automotive Trickle Chargers',
  'Garage Jacks',
  'High Pressure Air Foot Pumps',
  'Jack Stands',
  'Oil Capture Containers',
  'Timing lights',
  'Valve Spring Compressor'},
 'Trolly Jacks': {'Trolly Jacks'},
 'Vise Grips': {'Vise Grips'},
 'Buffers': {'Buffers'},
 'Slip Joint Pliers': {'Slip Joint Pliers'},
 'Cordless Screwdrivers': {'Cordless Screwdrivers'},
 'Drywall Tool Sets': {'Drywall Tool Sets'},
 'Drywall Tools': {'Bucket Scoops',
  'Drywall Circle Cutters',
  'Drywall Tool Sets',
  'Drywall Tools',
  'Joint Knives'},
 'Scroller Power Saws': {'Scroller Power Saws'},
 'Sharp Bristle Brushes': {'Sharp Bristle Brushes'},
 'Testers': {'Battery Testers',
  'Circuit Testers',
  'Testers',
  'Voltage Tester'},
 'Battery Testers': {'Battery Testers'},
 'Calipers': {'Calipers'},
 'Post Hole Diggers': {'Post Hole Diggers'},
 'Fencing Tools': {'Fence Come Along',
  'Fence Crimp Tool',
  'Fence Cutter',
  'Fence Post Pullers',
  'Fence Tensioner',
  'Fence Tie Winder',
  'Fencing Tools',
  'Gas Post Hole Diggers',
  'Post Drivers',
  'Post Hole Diggers'},
 'Sanders & Planers': {'Belt Sanders',
  'Combo Power Sanders',
  'Detail Sanders',
  'Drum Floor Sanders',
  'Edger Floor Sanders',
  'Finishing Power Sanders',
  'Floor Sanders',
  'Mouse Sanders',
  'Orbital Floor Sanders',
  'Palm Sanders',
  'Power Planers',
  'Power Sanders',
  'Random Orbit Sanders',
  'Sanders & Planers'},
 'Random Orbit Sanders': {'Random Orbit Sanders'},
 'Finishing Power Sanders': {'Finishing Power Sanders'},
 'Belt Sanders': {'Belt Sanders'},
 'Torque Wrench': {'Torque Wrench'},
 'Locks and Security': {'Locks and Security'},
 'Tap and Die': {'Tap and Die'},
 'Hand Shovel': {'Hand Shovel'},
 'Planters': {'Planters'},
 'Pitchfork': {'Pitchfork'},
 'Hand Trucks': {'Hand Trucks'},
 'Material Handling Equipment': {'Hand Trucks',
  'Loading Ramps',
  'Material Handling Equipment',
  'Pallet Jacks'},
 'Lights': {'Lights', 'Work Lights'},
 'Electronics': {'AR Gear',
  'Apps',
  'Audio',
  'Barcode & RFID Scanners',
  'Calculators',
  'Car Electronics',
  'Communications Devices',
  'Computers',
  'Data Storage Devices',
  'Drones',
  'Electronics',
  'Internet of Things',
  'Inverters',
  'Lighting',
  'Lighting Accessories',
  'Lights',
  'LightÂ\xading ConÂ\xadtrolÂ\xadlers',
  'Microcontroller Kits',
  'Microcontrollers',
  'Mobile Hotspots',
  'Network Equipment',
  'Other Electronic Devices',
  'Other Mobile Devices',
  'Payment Terminals',
  'Power',
  'Printers & Scanners',
  'Robots',
  'Sensors',
  'Shredders',
  'Signage & Displays',
  'Smartphones',
  'Software',
  'Tablets',
  'VR Gear',
  'Video & Photography',
  'Video Gaming',
  'White Noise Machines'},
 'Work Lights': {'Clamp Lights',
  'Hanging Lights',
  'Standing Work Lights',
  'Work Lights'},
 'Drill Press (hand)': {'Drill Press (hand)'},
 'Staple Guns': {'Manual Staple Guns', 'Roofing Stapler', 'Staple Guns'},
 'C-Clamps': {'C-Clamps'},
 'Tin Snips': {'Tin Snips'},
 'Tube Cutters': {'Tube Cutters'},
 'Pipe Cutters': {'Pipe Cutters'},
 'Rubber Mallets': {'Rubber Mallets'},
 'Crowbars': {'Crowbars'},
 'Lawn Mower': {'Lawn Mower'},
 'Cordless Mowers': {'Cordless Mowers'},
 'Shears': {'Edging Shears', 'Grass Shears', 'Metal Shears', 'Shears'},
 'Reciprocating Saws': {'Reciprocating Saws'},
 'Trowels & Floats': {'Brick Trowel',
  'Corner Trowel',
  'Float',
  'Grout Trowel',
  'Margin Trowel',
  'Notched Trowel',
  'Trowel',
  'Trowels & Floats',
  'Tuck Point Trowel'},
 'Notched Trowel': {'Notched Trowel'},
 'Chalklines': {'Chalklines'},
 'Pipe Wrenches': {'Pipe Wrenches'},
 'Caulk Guns': {'Caulk Guns'},
 'Die Grinders': {'Die Grinders'},
 'Conduit Benders': {'Conduit Benders'},
 'Socket Sets': {'Socket Sets'},
 'Wrench Sets': {'Allen Wrench Sets',
  'Box Wrench Sets',
  'Combination Wrench Sets',
  'Jumbo Wrench Sets',
  'Mixed Wrench Sets',
  'Open End Wrench Sets',
  'Ratcheting Wrench Sets',
  'Socket Sets',
  'Spark Plug Wrench Set',
  'Wrench Sets'},
 'Crow Bar with Chisel Ends': {'Crow Bar with Chisel Ends'},
 'Loppers': {'Loppers'},
 'Machete': {'Machete', 'Sickle'},
 'Wire Cutters': {'Wire Cutters'},
 'Needle Nose Pliers': {'Needle Nose Pliers'},
 'Squares': {'Squares'},
 'Seeders': {'Broadcast Seeders',
  'Hand Seeders',
  'Seeders',
  'Seeding Trays',
  'Wheel Seeders'},
 'Tenon Saws': {'Tenon Saws'},
 'Hand Miter Saws': {'Hand Miter Saws'},
 'Rivet Tools': {'Rivet Tools'},
 'Cordless Circular Saw': {'Cordless Circular Saw'},
 'Hatchet': {'Hatchet'},
 'Bow Saws': {'Bow Saws'},
 'Sledgehammers': {'Sledgehammers'},
 'String Trimmers': {'String Trimmers'},
 'Wet-Dry Vac': {'Wet-Dry Vac'},
 'Vacuum Cleaners': {'Handheld Vacuums',
  'Upright Vacuums',
  'Vacuum Cleaners',
  'Wet-Dry Vac'},
 'Soldering & Heat Guns': {'Heat Gun',
  'Hot Glue Gun',
  'Soldering & Heat Guns',
  'Soldering Iron'},
 'Squeegees': {'Squeegees'},
 'Sewing Machines': {'Sewing Machines'},
 'Hobbies & Crafts': {'Badge Makers',
  'Bottle Cutters',
  'Button Makers',
  'Hobbies & Crafts',
  'Hobby & Craft Kits',
  'Journals',
  'Knitting & Crocheting',
  'Model Making Tools',
  'Scissors',
  'Sewing Machines'},
 'Paint Sprayer': {'Paint Sprayer'},
 'Hand Tillers': {'Hand Tillers'},
 'Corded Miter Saws': {'Compound Miter Saws',
  'Corded Miter Saws',
  'Sliding Compound Miter Saws'},
 'Jig Saws': {'Jig Saws'},
 'Yardsticks': {'Yardsticks'},
 'Rulers': {'Rulers'},
 'Electric Dehydrators': {'Electric Dehydrators'},
 'Wedge': {'Wedge'},
 'Grinding Stones': {'Grinding Stones'},
 'Stud finder': {'Stud finder'},
 'Soldering Iron': {'Soldering Iron'},
 'Hack Saws': {'Hack Saws'},
 'Sickle': {'Sickle'},
 'Dollies': {'Dollies'},
 'Hex Keys': {'Hex Keys'},
 'Files': {'Files'},
 'Files, Awls & Punches': {'Auto Center Punches',
  'Awls',
  'Center Punches',
  'Files',
  'Files, Awls & Punches',
  'Punches',
  'Rasps'},
 'Routers': {'Plunge Routers', 'Routers', 'Trim Routers'},
 'Rotary Tools': {'Dremel Multi Pro', 'Rotary Tools', 'Roto Zip'},
 'Mixers & Dispensers': {'Masons Hawk', 'Mixers & Dispensers'},
 'Lawn Care (other)': {'Lawn Care (other)'},
 'Watering Tools': {'Watering Cans', 'Watering Tools'},
 'Cultivators': {'Cultivators'},
 'Bike Tools': {'Bike Keys',
  'Bike Pressure Gauges',
  'Bike Repair Stands',
  'Bike Tools',
  'Bottom Bracket Tools',
  'Brakes, Housing & Cable Tools',
  'Drive Train Tools',
  'Headset Tools',
  'Wheel Tools'},
 'Bottom Bracket Tools': {'Bottom Bracket Tools'},
 'Brakes, Housing & Cable Tools': {'Brakes, Housing & Cable Tools'},
 'Drive Train Tools': {'Drive Train Tools'},
 'Headset Tools': {'Headset Tools'},
 'Wheel Tools': {'Wheel Tools'},
 'Bike Keys': {'Bike Keys'},
 'Testers (hand held)': {'Testers (hand held)'},
 'Radial Arm Saws': {'Radial Arm Saws'},
 'Kitchen & Dining': {'Appliances',
  'Bottles',
  'Canning, Preserving & Homebrew',
  'Carafes',
  "Cook's Tools",
  'Cookbooks',
  'Cookware & Bakeware',
  'Cutlery',
  'Cutting Boards',
  'Dish Pans',
  'Drinking Glasses',
  'Food Containers',
  'Food Items',
  'Food Service Displays',
  'Food Storage',
  'Glassware & Drinkware',
  'Induction Cooking',
  'Kitchen & Dining',
  'Kitchen & Table Linens',
  'Kitchen Appliances',
  'Kitchen Gadgets',
  'Kitchen Tools',
  'Other Kitchen & Serving',
  'Plates & Bowls',
  'Pots & Pans',
  'Seeds',
  'Serving Trays',
  'Serving Utensils',
  'Small Appliances',
  'Thermoses',
  'Utensils',
  'Vacuum Flasks'},
 'root': {'Art',
  'Assistive Technology',
  'Books & Media',
  'Clothing',
  'Education',
  'Electrical Equipment',
  'Electronics',
  'Emergency Response',
  'Furniture & Spaces',
  'Hobbies & Crafts',
  'Kids & Baby',
  'Kitchen & Dining',
  'Medical Equipment',
  'More',
  'Music',
  'Office & Industrial',
  'Party & Events',
  'Science & Engineering',
  'Sports & Outdoors',
  'Toys & Games',
  'Vehicles & Trailers'},
 'Canning, Preserving & Homebrew': {'Canning Tools',
  'Canning, Preserving & Homebrew',
  'Fermenting Crocks'},
 'Appliances': {'Appliances'},
 "Cook's Tools": {"Cook's Tools"},
 'Cookware & Bakeware': {'Baking Pans',
  'Baking Tools & Accessories',
  'Cookware & Bakeware'},

In [12]:
# Use loans, our inventory table, and a dump of item types from MyTurn to generate statistics about each "Item Type" we have inventory for.
#
# The "Item Type" is MyTurn's way of bucketing items. You may have many difference sizes
# of box wrench, but they'll all have "Box Wrench" as the "Item Type", allowing us to
# understand trends/loan categories as a group.
import pandas as pd

# An empty list of the result
rows = []

# Index loans by "Item ID" so we can speed up lookups below
loans_by_item_id = loans.set_index('Item ID')

for ix, item_type in item_types.iterrows():
    # Pull a list of items for this item_type or its descendants
    items = inventory[
        inventory['Item Type'].isin(descendants[item_type['Type']])
    ]
    item_type_count = len(descendants[item_type['Type']])
    count = items['Item ID'].count()
    disabled_count = items[items['Disabled'] | items['In Maintenance'] | items['Wish List']]['Item ID'].count()
    active_count = count - disabled_count

    # Determine the maximum number of items checked out at once.
    #
    # This is easier than it sounds. We just grab all the check-in/out dates and increment the check-out
    # count when we encounter a check-out, decrement on a check-in. It doesn't matter which item specifically
    # is checked-out/checked-in.
    item_loans = loans_by_item_id[loans_by_item_id.index.isin(items['Item ID'])]
    
    loan_dates = []
    for _, loan in item_loans.iterrows():
        loan_dates.append({'type': 'CHECKOUT', 'date': loan['Checked Out']})
        
        if pd.notna(loan['Checked In']):
            # After 6 months, treat the item as lost (non concurrently checked out)
            loan_dates.append({
                'type': 'CHECKIN',
                'date': min(loan['Checked In'], loan['Checked Out'] + pd.Timedelta(weeks=25))
            })

    # Sort them in ascending order by date
    loan_dates.sort(key=lambda d: d['date'])

    max_checked_out = 0
    max_checked_out_date = None
    checked_out = 0
    for ld in loan_dates:
        if ld['type'] == 'CHECKOUT':
            checked_out += 1
            if checked_out > max_checked_out:
                max_checked_out = checked_out
                max_checked_out_date = ld['date']
        else:
            checked_out -= 1
            
    rows.append({
        'Item Type': item_type['Type'], 'Types Of Items': item_type_count,
        'Item Count': count, 'Disabled Item Count': disabled_count, 'Active Item Count': active_count,
        'Max Checked Out': max_checked_out, 'Max Checked Out Date': max_checked_out_date
    })

item_type_stats = pd.DataFrame(rows)
item_type_stats = item_type_stats.set_index(keys=['Item Type'])

item_type_stats

[{'type': 'CHECKOUT', 'date': Timestamp('2016-01-18 15:50:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-01-28 07:18:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-02-05 19:08:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-02-05 19:15:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-02-28 10:20:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-02-28 10:20:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-05-08 17:24:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-05-11 18:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-05-11 18:29:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-05-15 16:30:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-05-15 16:31:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-05-18 18:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-05-22 17:25:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-05-22 18:30:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-05-28 10:24:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-05-28 11:54:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-05-29 16:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-05-29 16:40:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-06-01 18:55:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-06-04 09:49:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-06-05 16:34:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-06-05 16:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-06-05 17:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-06-12 16:53:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-06-15 18:37:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-06-18 11:51:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-06-18 12:38:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-06-22 20:41:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-06-29 18:07:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-06-29 19:01:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-06-29 20:42:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-07-02 11:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-07-06 18:26:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-07-06 19:45:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-07-09 11:13:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-07-10 17:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-07-13 18:27:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-07-13 20:22:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-07-13 20:22:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-07-16 11:35:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-07-20 18:20:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-07-20 18:36:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-07-20 18:36:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-07-23 09:21:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-07-23 10:50:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-07-24 17:08:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-07-29 20:05:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-07-31 17:56:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-08-02 18:41:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-08-07 16:44:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-08-07 17:21:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-08-07 17:21:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-08-10 19:37:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-08-14 16:46:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-08-14 18:00:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-08-21 16:29:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-08-21 17:03:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-08-24 18:31:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-08-24 19:04:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-08-28 16:39:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-04 18:20:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-04 20:34:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-07 18:11:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-07 18:24:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-07 19:33:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-07 21:10:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-10 11:20:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-10 11:45:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-10 11:45:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-11 18:34:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-14 19:37:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-14 20:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-17 09:36:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-17 09:36:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-17 09:36:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-17 11:10:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-18 16:12:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-18 16:37:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-18 17:21:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-18 19:01:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-18 19:01:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-21 18:32:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-21 18:34:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-24 09:58:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-25 16:38:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-25 18:41:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-28 19:14:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-28 19:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-01 09:14:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-01 09:42:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-01 09:42:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-01 09:42:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-01 09:43:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-01 09:43:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-02 18:54:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-05 19:55:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-05 20:39:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-08 09:45:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-08 11:26:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-08 11:54:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-09 16:16:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-09 18:23:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-12 18:51:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-12 20:08:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-15 10:45:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-15 10:46:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-16 18:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-16 18:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-16 18:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-16 18:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-16 18:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-19 18:07:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-19 18:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-19 20:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-26 18:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-26 18:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-26 19:34:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-26 20:23:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-29 10:50:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-29 11:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-29 11:47:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-30 16:38:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-30 18:14:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-30 18:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-30 18:28:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-30 18:30:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-30 18:40:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-02 20:48:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-06 16:08:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-07 08:01:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-09 19:35:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-09 20:40:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-12 09:35:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-13 17:55:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-13 17:55:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-13 18:14:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-16 18:42:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-16 19:19:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-16 20:09:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-19 11:04:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-19 11:04:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-19 11:41:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-20 16:48:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-23 18:03:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-11-26 11:21:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-26 11:48:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-27 16:40:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-30 19:25:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-30 19:25:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-11-30 20:05:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-03 12:09:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-03 12:09:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-04 16:19:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-04 16:19:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-04 17:09:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-04 18:40:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-04 18:41:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-07 20:08:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-07 20:08:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-10 11:41:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-10 11:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-10 17:35:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-10 17:35:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-11 18:33:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-14 19:02:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-14 19:06:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-15 21:06:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-17 10:00:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-17 11:44:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-17 12:15:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-17 19:07:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-17 19:07:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-18 17:02:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-18 17:06:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-21 18:54:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-21 19:24:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-21 19:25:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-21 20:21:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-24 11:53:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-28 18:30:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-28 19:03:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-28 20:04:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-12-31 11:06:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-31 11:47:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-12-31 11:47:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-04 19:00:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-04 19:10:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-04 19:10:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-07 09:14:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-07 09:19:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-07 10:10:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-08 15:39:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-08 16:19:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-08 18:34:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-08 18:39:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-08 18:39:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-11 18:06:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-11 18:42:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-11 18:45:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-11 19:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-11 19:50:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-11 19:55:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-11 19:58:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-11 20:05:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-11 20:21:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-11 20:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-14 10:26:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-14 12:14:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-15 18:29:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-15 18:34:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-18 18:58:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-18 20:20:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-22 16:12:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-22 17:11:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-22 17:14:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-22 18:40:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-22 18:40:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-22 18:40:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-22 18:44:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-22 18:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-22 18:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-22 18:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-22 18:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-22 18:46:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-25 19:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-25 19:41:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-25 21:30:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-29 17:17:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-01-29 17:19:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-01 18:02:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-01 18:02:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-01 18:26:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-01 19:14:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-01 19:29:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-05 17:50:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-05 18:42:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-05 18:42:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-05 18:53:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-08 18:10:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-11 10:20:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-11 10:42:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-12 17:03:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-12 17:14:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-12 17:14:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-12 17:14:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-15 19:04:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-15 20:41:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-15 20:48:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-18 11:04:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-18 11:38:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-18 11:38:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-18 11:38:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-18 11:38:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-18 11:57:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-18 11:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-19 18:13:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-19 18:13:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-19 18:13:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-19 18:13:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-19 18:13:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-22 19:47:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-22 19:47:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-22 19:47:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-22 20:00:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-25 10:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-25 11:06:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-25 11:06:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-25 11:06:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-25 11:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-25 11:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-02-25 11:57:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-02-26 17:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-01 20:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-01 20:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-01 20:27:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-04 10:30:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-04 11:25:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-04 11:56:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-08 19:11:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-08 19:37:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-08 20:59:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-08 20:59:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-08 20:59:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-11 09:49:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-11 10:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-11 11:59:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-12 17:47:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-12 17:47:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-12 19:02:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-12 19:02:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-15 18:30:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-15 18:38:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-15 18:38:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-15 18:38:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-18 12:16:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-19 18:43:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-19 18:43:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-19 18:43:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-22 19:05:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-22 20:25:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-25 09:59:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-25 09:59:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-25 10:45:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-25 11:11:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-25 11:11:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-25 11:52:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-26 17:31:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-26 17:31:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-26 17:31:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-03-26 17:57:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-26 18:44:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-26 18:51:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-26 19:06:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-03-29 18:06:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-04-01 09

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

[{'type': 'CHECKOUT', 'date': Timestamp('2016-09-03 11:55:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-18 19:01:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-12-16 09:14:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-12-16 09:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2018-06-20 16:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2018-07-14 11:31:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2019-08-11 16:48:00')}, {'type': 'CHECKIN', 'date': Timestamp('2019-08-17 11:44:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2019-08-19 18:36:00')}, {'type': 'CHECKIN', 'date': Timestamp('2019-08-21 18:40:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2019-10-28 19:52:00')}, {'type': 'CHECKIN', 'date': Timestamp('2020-04-20 19:52:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2020-08-29 09:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2020-09-12 11:04:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2021-09-11 12:00:00')}, {'type': 'CHECKIN', 'date': Timestamp('2021-09-28 19:53:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2021-12-04 11:46:00')}, {'type': 'CHECKIN', 'date': Timestamp('2021-12-08 20:16:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-04-13 11:38:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-04-29 18:44:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-06-27 20:32:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-07-20 10:04:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2025-10-30 19:16:00')}]
[{'type': 'CHECKOUT', 'date': Timestamp('2024-02-10 11:33:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-02-10 11:33:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-02-10 11:33:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-02-10 11:33:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-04-14 17:31:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-04-14 17:31:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-04-14 17:31:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-04-14 17:31:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-05-12 16:02:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-05-19 18:03:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-08-28 18:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-09-11 18:35:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-12-03 20:37:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-12-03 20:37:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-12-14 11:55:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-12-14 11:55:00')}]
[]
[{'type': 'CHECKOUT', 'date': Timestamp('2017-09-13 16:12:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-09-13 16:12:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-09-20 15:56:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-09-20 15:56:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2018-11-06 19:41:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2018-11-20 18:51:00')}, {'type': 'CHECKIN', 'date': Timestamp('2018-11-21 18:22:00')}, {'type': 'CHECKIN', 'date': Timestamp('2018-12-01 09:33:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2019-07-10 19:17:00')}, {'type': 'CHECKIN', 'date': Timestamp('2019-07-16 18:20:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2019-09-28 10:22:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2019-10-08 18:17:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2019-10-08 18:17:00')}, {'type': 'CHECKIN', 'date': Timestamp('2019-10-27 17:59:00')}, {'type': 'CHECKIN', 'date': Timestamp('2019-10-27 17:59:00')}, {'type': 'CHECKIN', 'date': Timestamp('2019-10-27 17:59:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2021-04-13 19:11:00')}, {'type': 'CHECKIN', 'date': Timestamp('2021-04-20 18:03:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2021-08-04 18:29:00')}, {'type': 'CHECKIN', 'date': Timestamp('2021-08-18 19:35:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-08-31 19:53:00')}, {'type': 'CHECKIN', 'date': Timestamp('2022-09-03 11:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-11-23 19:20:00')}, {'type': 'CHECKIN', 'date': Timestamp('2022-12-07 19:25:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-11-22 18:47:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-12-09 09:48:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-01-16 18:14:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-01-21 16:29:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-05-29 18:20:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-06-22 11:05:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-08-08 18:03:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-08-29 20:11:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2025-04-30 18:31:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2025-08-07 19:15:00')}, {'type': 'CHECKIN', 'date': Timestamp('2025-08-09 11:51:00')}]
[{'type': 'CHECKOUT', 'date': Timestamp('2018-10-28 19:05:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2018-11-21 20:46:00')}, {'type': 'CHECKIN', 'date': Timestamp('2018-11-21 20:46:00')}, {'type': 'CHECKIN', 'date': Timestamp('2018-12-01 11:34:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-07-20 19:01:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-07-20 19:01:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-07-31 18:12:00')}, {'type': 'CHECKIN', 'date': Timestamp('2022-08-13 10:21:00')}, {'type': 'CHECKIN', 'date': Timestamp('2022-08-13 10:21:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-01-22 18:12:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-08-30 19:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-08-30 19:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-08-30 19:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-10-21 10:07:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-10-29 15:59:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-10-29 15:59:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-10-29 15:59:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-12-09 10:41:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-06-12 18:55:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-08-11 17:26:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-08-17 09:12:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-09-24 19:20:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-11-24 14:05:00')}]
[{'type': 'CHECKOUT', 'date': Timestamp('2018-10-28 19:05:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2018-11-21 20:46:00')}, {'type': 'CHECKIN', 'date': Timestamp('2018-11-21 20:46:00')}, {'type': 'CHECKIN', 'date': Timestamp('2018-12-01 11:34:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-07-20 19:01:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-07-20 19:01:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-07-31 18:12:00')}, {'type': 'CHECKIN', 'date': Timestamp('2022-08-13 10:21:00')}, {'type': 'CHECKIN', 'date': Timestamp('2022-08-13 10:21:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-01-22 18:12:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-08-30 19:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-08-30 19:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-08-30 19:15:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-10-21 10:07:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-10-29 15:59:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-10-29 15:59:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-10-29 15:59:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-12-09 10:41:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-06-12 18:55:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-08-11 17:26:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-08-17 09:12:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-09-24 19:20:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-11-24 14:05:00')}]
[]
[{'type': 'CHECKOUT', 'date': Timestamp('2016-08-31 18:44:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-09-04 18:25:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-09-23 15:27:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-06 18:39:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2016-10-12 20:14:00')}, {'type': 'CHECKIN', 'date': Timestamp('2016-10-19 18:46:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-01-11 19:28:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2017-06-24 11:08:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-07-05 19:28:00')}, {'type': 'CHECKIN', 'date': Timestamp('2017-07-12 20:35:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2018-01-03 21:07:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2018-04-11 19:02:00')}, {'type': 'CHECKIN', 'date': Timestamp('2018-06-27 21:07:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2018-08-26 18:51:00')}, {'type': 'CHECKIN', 'date': Timestamp('2018-10-03 19:02:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2018-12-22 10:23:00')}, {'type': 'CHECKIN', 'date': Timestamp('2019-02-17 18:51:00')}, {'type': 'CHECKIN', 'date': Timestamp('2019-02-17 19:09:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2019-12-09 19:17:00')}, {'type': 'CHECKIN', 'date': Timestamp('2019-12-15 17:42:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2020-01-12 16:11:00')}, {'type': 'CHECKIN', 'date': Timestamp('2020-02-05 19:47:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2020-06-27 11:29:00')}, {'type': 'CHECKIN', 'date': Timestamp('2020-07-04 11:53:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2020-07-25 10:07:00')}, {'type': 'CHECKIN', 'date': Timestamp('2020-08-08 10:33:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2021-01-16 12:19:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2021-04-27 20:17:00')}, {'type': 'CHECKIN', 'date': Timestamp('2021-05-08 11:55:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2021-05-15 10:42:00')}, {'type': 'CHECKIN', 'date': Timestamp('2021-05-29 11:35:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2021-06-19 11:57:00')}, {'type': 'CHECKIN', 'date': Timestamp('2021-07-10 12:19:00')}, {'type': 'CHECKIN', 'date': Timestamp('2021-07-13 19:31:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-04-30 09:38:00')}, {'type': 'CHECKIN', 'date': Timestamp('2022-06-21 19:56:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2022-06-22 19:34:00')}, {'type': 'CHECKIN', 'date': Timestamp('2022-07-09 12:03:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-01-18 19:45:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-04-15 10:54:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-08-05 11:03:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2023-09-20 19:15:00')}, {'type': 'CHECKIN', 'date': Timestamp('2023-09-30 11:40:00')}, {'type': 'CHECKOUT', 'date': Timestamp('2024-04-06 11:40:00')}, {'type': 'CHECKIN', 'date': Timestamp('2024-09-28 11:40:00')}]

,Types Of Items,Item Count,Disabled Item Count,Active Item Count,Max Checked Out,Max Checked Out Date
Item Type,,,,,,
Hand Tools,81,1833,675,1158,277,2025-10-16 19:58:00
Power Tools,8,63,16,47,20,2025-07-19 11:47:00
Shovels & Digging,11,65,18,47,28,2025-09-21 17:05:00
Rakes,12,48,12,36,18,2025-05-18 17:59:00
Pruners,5,45,9,36,26,2024-09-26 18:56:00
...,...,...,...,...,...,...
Baby Bath Stands,1,0,0,0,0,NaT
Baby Bouncers,1,0,0,0,0,NaT
Breast Pumps Electric Single,1,0,0,0,0,NaT
Breast Pumps Electric Double,1,0,0,0,0,NaT
Breast Pumps Manual,1,0,0,0,0,NaT

In [4]:
# Add a column representing the "utilization" of the item.
#
# For now, we're counting utilization as the maximum number checked out ever, divided by the current number of active items.

with_inventory = item_type_stats[item_type_stats['Item Count'] > 0]

with_utilization = pd.DataFrame(with_inventory)
# Round percentages to the nearest whole number for simplicity
with_utilization['Utilization'] = (100 * with_utilization['Max Checked Out'] / with_utilization['Active Item Count']).round(1)

with_utilization.sort_values(by=['Utilization'], ascending=False)

,Types Of Items,Item Count,Disabled Item Count,Active Item Count,Max Checked Out,Max Checked Out Date,Utilization
Item Type,,,,,,,
Storage Furniture,1,1,1,0,1,2021-03-30 20:10:00,inf
Distance Meters,1,1,1,0,1,2019-12-23 18:46:00,inf
Wired Mice,1,1,1,0,1,2022-06-22 20:02:00,inf
Electric Chippers,1,1,1,0,1,2020-09-26 10:49:00,inf
Cubicles,1,1,1,0,1,2022-11-22 19:53:00,inf
...,...,...,...,...,...,...,...
House Wash Brushes,1,1,1,0,0,NaT,NaN
Uninterruptible Power Supplies (UPS),1,1,1,0,0,NaT,NaN
Stage & Screen,10,1,1,0,0,NaT,NaN
Video Switchers,1,1,1,0,0,NaT,NaN
Bags,6,1,1,0,0,NaT,NaN

In [5]:
# Print the item_type_stats with the "Utilization" column in the order the "Item Type"s are listed in the
# original data/input/item_types.csv (ordered in depth first search order).

with_utilization.to_csv('/home/max/chtl/data/reports/item_type_stats.csv')
with_utilization.to_pickle('/home/max/chtl/data/reports/item_type_stats.pkl')

In [6]:
with_utilization.sort_values(by='Utilization', ascending=False).to_csv('/home/max/chtl/data/reports/temp_item_type_stats_sorted.csv')

In [7]:
# This table is challenging to use.
#
# * The peak utilization is sometimes a weird checkout - like the one user who checked out 3 hatches at once and got robbed.
# * Very specific item categories cause a lot of noise ("Crowbar With Chisel Ends"). I don't actually care if we're out of
#   these, just whether users can get a crowbar. Not sure if I should make a list of these and exclude/mark them, if there's
#   an underlying problem with MyTurn's Item Types, or if I should hide/group this.

In [8]:
with_utilization.loc[['Hammer Drills']]

,Types Of Items,Item Count,Disabled Item Count,Active Item Count,Max Checked Out,Max Checked Out Date,Utilization
Item Type,,,,,,,
Hammer Drills,1,7,3,4,4,2025-05-19 19:59:00,100.0

In [9]:
# TODO: Is this actually useful?
#
# * When sub-item types are similar, it can raise a false alarm (no "Crowbars", but plenty of "Crowbars With Chisel Ends")

In [10]:
# Okay, let's redo. Go through items and group, not by item types.abs

# Use loans, our inventory table, and a dump of item types from MyTurn to generate statistics about each "Item Type" we have inventory for.
#
# The "Item Type" is MyTurn's way of bucketing items. You may have many difference sizes
# of box wrench, but they'll all have "Box Wrench" as the "Item Type", allowing us to
# understand trends/loan categories as a group.
import pandas as pd
from dataclasses import dataclass

@dataclass
class ItemTypeCounts:
    item_count: int
    loan_count: int

# An empty list of the result
rows = []

# Index loans by "Item ID" so we can speed up lookups below
loans_by_item_id = loans.set_index('Item ID')


item_type_counts = defaultdict(lambda: ItemTypeCounts(0, 0))

for ix, item in inventory.iterrows():
    # Determine the maximum number of items checked out at once.
    #
    # This is easier than it sounds. We just grab all the check-in/out dates and increment the check-out
    # count when we encounter a check-out, decrement on a check-in. It doesn't matter which item specifically
    # is checked-out/checked-in.
    loan_count = 0
    if item['Item ID'] in loans_by_item_id:
        loan_count = len(loans_by_item_id[item['Item ID']])
    
    c = item_type_counts[item['Item Type']]
    c.item_count += 1
    c.loan_count += len(item_loans)


for item_type, counts in item_type_counts.items():
    rows.append({
        'Item Type': item_type,
        'Item Count': counts.item_count,
        'Loan Count': counts.loan_count
    })
simple_stats = pd.DataFrame(rows)
simplestats = simple_stats.set_index(keys=['Item Type'])

In [11]:
simple_stats.to_csv('/home/max/chtl/data/reports/simple_stats.csv')